# Generated by Django 3.0.8 on 2021-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_planner',
            field=models.BooleanField(default=False, verbose_name='Is planner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Is teacher'),
        ),
    ]
