# Generated by Django 3.0.8 on 2021-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211023_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Class',
            field=models.CharField(choices=[['--', '--'], ['1A', '1A'], ['1B', '1B'], ['1C', '1C'], ['2A', '2A'], ['2B', '2B'], ['3C', '2C']], default=1, max_length=2, verbose_name='Class'),
        ),
    ]
