# Generated by Django 3.0.8 on 2021-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[['pl', 'Polish'], ['en-us', 'English']], default=1, max_length=5, verbose_name='Language'),
        ),
    ]
