# Generated by Django 3.0.8 on 2021-11-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
    ]
