# Generated by Django 3.0.8 on 2021-11-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20211101_1500'),
        ('accounts', '0005_remove_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='planner.Class'),
        ),
    ]
