# Generated by Django 3.0.8 on 2021-11-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211101_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Class',
        ),
    ]
