# Generated by Django 3.0.8 on 2021-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_class_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsettings',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customsettings',
            name='time_interval',
        ),
        migrations.AddField(
            model_name='customsettings',
            name='language',
            field=models.CharField(choices=[['pl', 'Polish'], ['en-us', 'English']], default=1, max_length=5, verbose_name='Language'),
        ),
    ]
