# Generated by Django 3.0.8 on 2021-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20211101_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='class_name',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
