# Generated by Django 3.0.8 on 2021-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20211101_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lesson Name')),
            ],
        ),
    ]
