# Generated by Django 3.0.8 on 2021-11-09 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes', to='planner.Class'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='Date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 9, 15, 22, 25, 20155), verbose_name='Date start'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='Date_stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 9, 15, 22, 25, 20155), verbose_name='Date stop'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rooms', to='planner.Rooms'),
        ),
    ]
